### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sebiweise** [Fasse/admidio-statistics#11]
### Description

I´m getting the following error when trying to install statistics:

```shell
PHP Fatal error:  Uncaught Error: Call to a member function rowCount() on bool in /opt/app-root/src/adm_plugins/statistics/utils/db_access.php:41\nStack trace:\n#0 /opt/app-root/src/adm_plugins/statistics/utils/db_access.php(26): DBAccess->pluginIsInstalled()\n#1 /opt/app-root/src/adm_plugins/statistics/install/install.php(209): DBAccess->__construct()\n#2 /opt/app-root/src/adm_plugins/statistics/install/install.php(148): addStatisticTemplates()\n#3 /opt/app-root/src/adm_plugins/statistics/install/install.php(62): startInstallation()\n#4 {main}\n  thrown in /opt/app-root/src/adm_plugins/statistics/utils/db_access.php on line 41, referer: https://admidio.sebastianweise.com/adm_plugins/statistics/install/install.php
```

### Steps to Reproduce

1. Install Admidio using Docker
2. Install the admidio-statistics plugin into the plugin folder
3. Navigate to /adm_plugins/statistics/install/install.php and select Installation

**Expected behavior:**

The plugin should be install.

**Actual behavior:**

```shell
PHP Fatal error:  Uncaught Error: Call to a member function rowCount() on bool in /opt/app-root/src/adm_plugins/statistics/utils/db_access.php:41\nStack trace:\n#0 /opt/app-root/src/adm_plugins/statistics/utils/db_access.php(26): DBAccess->pluginIsInstalled()\n#1 /opt/app-root/src/adm_plugins/statistics/install/install.php(209): DBAccess->__construct()\n#2 /opt/app-root/src/adm_plugins/statistics/install/install.php(148): addStatisticTemplates()\n#3 /opt/app-root/src/adm_plugins/statistics/install/install.php(62): startInstallation()\n#4 {main}\n  thrown in /opt/app-root/src/adm_plugins/statistics/utils/db_access.php on line 41, referer: https://admidio.sebastianweise.com/adm_plugins/statistics/install/install.php
```

HTTP Error 500

**Reproduces how often:**

Every time

### Versions

PostgreSQL-Version: 16.6
PHP-Version: 8.1.2-1ubuntu2.19
Contaienr image: admidio/admidio:branch_v4.3

### Additional Information

Installed on a Ubuntu Server 24.04 server with a standalone Docker installation

**Comment by sebiweise** [comment]
> 3\. /adm_plugins/statistics/install/install.php

Perfect thanks, fixed it.
